#!/bin/bash
#
# manage a group of: chatsercer + n*loginserver

prog="node --expose-gc"
server=""

RETVAL=0
_start() {

    name=$1
    args=$2
    pidfile="$1.pid"

    echo -n $"Starting $name .............."
    if [ -f $pidfile ]; then
        echo -e "\t\E[31;40m[FAIL]\033[0m"
        echo "$name is Running"
    else
        nohup $prog $args 1>/dev/null 2>&1 &
        for i in {1..5}; do
            if [ -f $pidfile ]; then
                echo -e "\t\E[32;40m[OK]\033[0m"
                break
            else
                if [ $i -eq 5 ]; then
                    echo -e "\t\E[31;40m[FAIL]\033[0m"
                fi
            fi
			
			if [[ $? -eq 0 ]]; then
				echo $!>${pidfile}
			fi
            sleep 1
        done
    fi
    RETVAL=$?
}

_stop() {
    name=$1
    pidfile="$1.pid"

    echo -n $"Stopping $name .............."
    if [ -f ${pidfile} ]; then
        pid=`cat ${pidfile}`
        if [ -d "/proc/${pid}" ]; then
            while [ -d "/proc/${pid}" ]; do
                kill  ${pid}
                sleep 1
            done
        fi
        rm -f ${pidfile}
    fi
    echo -e "\t\E[32;40m[OK]\033[0m"
    RETVAL=$?
}

_status() {
    name=$1
    pidfile="$1.pid"

    echo -n -e "$name\t\t"
    if [ -f ${pidfile} ]; then
        pid=`cat ${pidfile}`
        echo -n -e "$pid\t\t"
        if [ -d "/proc/${pid}" ]; then
            echo -n -e "\E[32;40m[Running]\033[0m\t"
        else
            echo -n -e "\E[31;40m[Lost]\033[0m\t\t"
        fi

        echo `ps -p $pid -o rss | tail -n 1 | awk '{printf("%.2fM", $1/1024)}'`
    else
        echo -e "-\t\t\E[31;40m[Stoped]\033[0m\t-"
    fi

    RETVAL=$?
}

start() {
    config='config.js'
    if [ -f '../config.js' ]; then
        config='../config.js'
    fi

    serverId=`grep exports.ServerId $config| awk '{print $3}' | awk -F';' '{print $1}'`
	phpHost=`grep "exports.PHPHost" $config | awk '{print $3}'`
	
    loginIdBegin=`grep exports.loginIdBegin $config| awk -F'[ ;]' '{print $3}'`
    loginCount=`grep exports.loginCount $config| awk -F'[ ;]' '{print $3}'`

    clean
	
	if [ "$server" =  "chatserver" ] || [ "$server" = "" ]; then
        _start chatserver 'chatserver.js'
    fi

    if [ "$server" =  "loginserver" ] || [ "$server" = "" ]; then
		for ((c=0; c<$loginCount; c++))
        do
            ((d=$loginIdBegin+c))

            _start "loginserver$d" "loginserver.js $d"
        done
    fi
}

stop() {
	config='config.js'
    if [ -f '../config.js' ]; then
        config='../config.js'
    fi
		
    if [ "$server" =  "loginserver" ] || [ -z "$server" ]; then
		loginIdBegin=`grep exports.loginIdBegin $config| awk -F'[ ;]' '{print $3}'`
		loginCount=`grep exports.loginCount $config| awk -F'[ ;]' '{print $3}'`
		
		for ((c=0; c<$loginCount; c++))
        do
            ((d=$loginIdBegin+c))
            _stop "loginserver$d"
        done
    fi
	
	if [ "$server" =  "chatserver" ] || [ "$server" = "" ]; then
        _stop chatserver
    fi
}

status() {
    echo -e "Version: `git log | head -n 1 | awk '{print $2}'`"
    echo "------------------------------------------------------"
    echo -e "Process\t\tPID\\t\tStatus\t\tMem"
	
	config='config.js'
    if [ -f '../config.js' ]; then
        config='../config.js'
    fi
	
	if [ "$server" =  "chatserver" ] || [ "$server" = "" ]; then
        _status chatserver
    fi

    if [ "$server" =  "loginserver" ] || [ "$server" = "" ]; then
		loginIdBegin=`grep exports.loginIdBegin $config| awk -F'[ ;]' '{print $3}'`
		loginCount=`grep exports.loginCount $config| awk -F'[ ;]' '{print $3}'`
		
		for ((c=0; c<$loginCount; c++))
        do
            ((d=$loginIdBegin+c))
            _status "loginserver$d"
        done
    fi
}

reload() {
    node reload
}

clean() {
    # 清理3日前日志
    find log -mtime +3 -name "*.*" -exec rm -rf {} \;
}

if [ $# -ge 2 ]; then
    case "$2" in
        loginserver|chatserver)
            server=$2
            ;;
        *)
            echo "arg 2 should in [loginserver|chatserver]"
            exit 1
    esac
fi

# See how we were called.
case "$1" in
  reload)
        reload
        ;;
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart)
        stop
        start
        ;;
  clean)
        clean
        ;;
  *)
        echo $"Usage: manage {start|stop|restart|status} [loginserver|chatserver]"
        exit 1
esac

exit $RETVAL
